apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission
  labels:
    app.kubernetes.io/component: admission-webhook
    {{- include "ingress-nginx.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - validatingwebhookconfigurations
    verbs:
    - get
    - update