apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    {{- include "ingress-nginx.labels" . | nindent 4 }}
data:
  allow-snippet-annotations: "true"
  http-snippet: |
    server {
      listen 2443;
      return 308 https://$host$request_uri;
    }
  proxy-real-ip-cidr: 10.0.0.0/16
  use-forwarded-headers: "true"