apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission-patch
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    {{- include "ingress-nginx.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "ingress-nginx.fullname" . }}-admission-patch
      labels:
        {{- include "ingress-nginx.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ingress-nginx.serviceAccountName" . }}-admission
      containers:
      - name: patch
        securityContext:
          allowPrivilegeEscalation: false
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: "{{ .Values.jobImage.repository }}:{{ .Values.jobImage.tag }}"
        imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
        args:
          - patch
          - --webhook-name=ingress-nginx-admission
          - --namespace=$(POD_NAMESPACE)
          - --patch-mutating=false
          - --secret-name=ingress-nginx-admission
          - --patch-failure-policy=Fail
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000