apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission-create
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    {{- include "ingress-nginx.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "ingress-nginx.fullname" . }}-admission-create
      labels:
        {{- include "ingress-nginx.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ingress-nginx.serviceAccountName" . }}-admission
      containers:
      - name: create
        securityContext:
          allowPrivilegeEscalation: false
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: "{{ .Values.jobImage.repository }}:{{ .Values.jobImage.tag }}"
        imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
        args:
          - create
          - --host=ingress-nginx-controller-admission,ingress-nginx-controller-admission.$(POD_NAMESPACE).svc
          - --namespace=$(POD_NAMESPACE)
          - --secret-name=ingress-nginx-admission
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000