apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    {{- include "ingress-nginx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ingress-nginx.fullname" . }}-admission
subjects:
  - kind: ServiceAccount
    name: {{ include "ingress-nginx.serviceAccountName" . }}-admission
    namespace: ingress-nginx