apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ingress-nginx.fullname" . }}-admission
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    {{- include "ingress-nginx.labels" . | nindent 4 }}
  rules:
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - get
      - create