apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ingress-nginx.fullname" . }}
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    {{- include "ingress-nginx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ingress-nginx.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ingress-nginx.serviceAccountName" . }}
    namespace: ingress-nginx