{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-nginx.serviceAccountName" . }}-admission
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: admission-webhook
    {{- include "ingress-nginx.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
