apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster.fullname" . }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster.serviceAccountName" . }}
    namespace: kube-system